### ISSUE TITLE
Could not find a valid gem 'pgn2tex' in any repository

### ISSUE THREAD

**Issue by oskarryn** [sigvei/pgn2tex#3]
Hey

I can't install pgn2tex despite good version of ruby (>1.9)

```
ruby --version
ruby 2.5.1p57 (2018-03-29 revision 63029) [x86_64-linux-gnu]
gem --version
2.7.6
sudo gem install pgn2tex
ERROR:  Could not find a valid gem 'pgn2tex' (>= 0) in any repository
```

**Comment by sigvei** [comment]
Hi Oskar,

This project was never really finished, and the README file is wrong. I guess the code could be used as it is now, but I did never come around to publishing it to the gem repositories.

You can try it out by installing it locally:

```bash
git clone https://github.com/sigvei/pgn2tex.git
cd pgn2tex
gem build pgn2tex.gemspec
gem install pgn2tex-0.0.1.gem
```

But I have no idea if it actually works. Sorry about this!
